@echo off
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Seeding database...
python scripts\seed.py
echo Starting server...
uvicorn app.main:app --reload
pause
